name: Deploy on gh-pages push

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Convert Markdown to React
      run: find src/pages -type d -not -path "*/__snapshots__" -exec npx ts-node --project ./scripts/tsconfig.json scripts/md-to-react.ts {} \;

    - name: Build Routes
      run: npx ts-node --project ./scripts/tsconfig.json scripts/build-routes.ts

    # TODO: Fix lint warnings to get rid of this step.
    - name: Override CI Environment Variable
      run: echo "CI=false" >> $GITHUB_ENV

    - name: Build
      env:
        SKIP_PREFLIGHT_CHECK: true
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.9
      with:
        branch: master   # The branch to deploy to
        folder: build    # The folder to deploy
